- hosts: ctf_x1
  gather_subset:
    - "!all"
  roles:
    # Basics
    - ssh_keys
    - unix_utils
    - git
    # Terminal env
    - bashrc
    - tmux
    - ssh
    - direnv
    # IDE
    - vim
    # devenv
    - sh_dev
    - workspace
    - chef
      #    - docker
    - aws
    - kubernetes
    - golang
    # GUI programs
    - zoom_us
    - chrome_config

- hosts: single_role
  roles:
    - "{{ role_to_run | default('') }}"
