- hosts: ctf_x1
  gather_subset:
    - "!all"
  roles:
    # Basics
    - ssh_keys
    - unix_utils
    - git
    # Terminal env
    - bashrc
    - tmux
    - ssh
    # IDE
    - vim
    # Infra tools
    - chef

- hosts: single_role
  roles:
    - "{{ role_to_run | default('') }}"
