- name: Create ~/.ssh
  file:
    path: ~/.ssh
    state: directory

- name: SSH Private key
  copy:
    content: "{{ lookup('onepassword_raw', 'SSH - private') | json_query('details.notesPlain') }}"
    dest: ~/.ssh/id_rsa
    mode: 0600

- name: SSH Public key
  copy:
    content: "{{ lookup('onepassword_raw', 'SSH - public') | json_query('details.notesPlain') }}"
    dest: ~/.ssh/id_rsa.pub
    mode: 0600
