- name: Install AWS CLI
  become: true
  apt:
    package: awscli

- name: Create ~/.aws
  file:
    path: ~/.aws
    state: directory

- name: bash setup
  include: roles/dotfiles/tasks/symlink.yml src=.bashrc.d/aws dest=~/.bashrc.d/30-aws
