- name: Symlink git configuration
  include: roles/dotfiles/tasks/symlink.yml src=.gitconfig

- name: Symlink gitignore
  include: roles/dotfiles/tasks/symlink.yml src=.gitignore_global

- name: Symlink gitprompt
  include: roles/dotfiles/tasks/symlink.yml src=.git-prompt.sh dest=~/.bashrc.d/22-git-prompt

- name: git bash setup
  include: roles/dotfiles/tasks/symlink.yml src=.bashrc.d/git dest=~/.bashrc.d/21-git

- name: Install git-so-fancy
  npm:
    name: diff-so-fancy
    global: true
