- name: Install Docker pre-install dependencies
  become: true
  apt:
    name: "{{ item }}"
    install_recommends: false
  with_items:
    - linux-image-extra-{{ ansible_kernel }}
    - linux-image-extra-virtual
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Add Docker APT repo GPG key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- name: Add Docker APT repo
  become: true
  apt_repository:
    # pinning to Zesty until there's an official release for Artful
    #repo: deb https://apt.dockerproject.org/repo/ ubuntu-{{ ansible_distribution_release }} main
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu artful    stable

- name: Install Docker
  become: true
  apt:
    name: docker-ce

- name: Create docker group
  group:
    name: docker

- name: Add user to docker group
  become: true
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: true

    #- name: Install docker-compose
    #  pip:
    #    virtualenv: ~/docker-compose
    #    virtualenv_python: python3
    #    name: docker-compose
    #
    #- name: Symlink docker-compose
    #  become: true
    #  file:
    #    src: "{{ ansible_env.HOME }}/docker-compose/bin/docker-compose"
    #    dest: /usr/local/bin/docker-compose
    #    state: link
